name: Submit Actions dependencies

on:
  workflow_dispatch:

jobs:
  submit-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Submit composite-action dependencies
        uses: jessehouwing/actions-dependency-submission@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          additional-paths: action.yml
